name: auto-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=25.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - zlib=1.2.13
  - xz=5.6.4
  - jupyter
  - notebook
  - ipykernel
  - nbconvert
  - pip:
    - langchain==0.3.19
    - langchain-community==0.3.18
    - langchain-core==0.3.58
    - langchain-openai==0.3.16
    - langchain-text-splitters==0.3.6
    - chromadb==0.6.3
    - fastapi==0.115.10
    - uvicorn[standard]
    - python-dotenv
    - openai==1.77.0
    - streamlit==1.42.2
    - pydantic==2.10.3
    - numpy
    - pandas
    - python-multipart
    - tqdm
    - typing-extensions
    - requests
    - sentence-transformers==4.1.0
    - aiohappyeyeballs==2.4.6
    - aiohttp==3.11.13
    - aiosignal==1.3.2
    - altair==5.5.0
    - annotated-types==0.7.0
    - anyio==4.8.0
    - argh==0.31.3
    - asgiref==3.8.1
    - async-timeout==4.0.3
    - attrs==25.1.0
    - backoff==1.11.1
    - bcrypt==4.3.0
    - blinker==1.9.0
# Remove bottleneck as it requires compilation
    # - bottleneck==1.4.2
    - brotli==1.0.9
    - build==1.2.2.post1
    - cachetools==5.5.2
    - certifi==2025.1.31
    - cffi==1.14.6
    - charset-normalizer==3.4.1
    - chroma-hnswlib==0.7.6
    - click==8.1.8
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - cryptography==44.0.1
    - dataclasses-json==0.6.7
    - deprecated==1.2.18
    - distro==1.9.0
    - dnspython==2.7.0
    - durationpy==0.9
    - email-validator==2.2.0
    - exceptiongroup==1.2.2
    - fastapi-cli==0.0.7
    - filelock==3.17.0
    - flatbuffers==25.2.10
    - frozenlist==1.5.0
    - fsspec==2025.2.0
    - gitdb==4.0.12
    - gitpython==3.1.44
# Remove gmpy2 as it requires compilation
    # - gmpy2==2.1.5
    - google-auth==2.38.0
    - googleapis-common-protos==1.68.0
    - greenlet==2.0.2
    - grpcio==1.62.2
    - h11==0.14.0
    - h2==4.2.0
    - hpack==4.1.0
    - httpcore==1.0.7
    - httptools==0.6.4
    - httpx==0.28.1
    - httpx-sse==0.4.0
    - huggingface-hub==0.30.2
    - humanfriendly==10.0
    - hyperframe==6.1.0
    - idna==3.10
    - importlib-metadata==8.5.0
    - importlib-resources==6.5.2
    - jinja2==3.1.5
    - jiter==0.6.1
    - joblib==1.5.0
    - jsonpatch==1.33
    - jsonpointer==2.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kubernetes==32.0.1
    - langsmith==0.2.11
    - markdown-it-py==3.0.0
    - markupsafe==2.0.1
    - marshmallow==3.26.1
    - mdurl==0.1.2
    - mmh3==5.1.0
    - monotonic==1.6
    - mpmath==1.3.0
    - multidict==5.2.0
    - mypy-extensions==1.0.0
    - narwhals==1.27.1
    - numexpr==2.10.1
    - oauthlib==3.2.2
    - olefile==0.47
    - onnxruntime==1.19.2
    - opentelemetry-api==1.30.0
    - opentelemetry-exporter-otlp-proto-grpc==1.15.0
    - opentelemetry-instrumentation==0.51b0
    - opentelemetry-instrumentation-asgi==0.51b0
    - opentelemetry-instrumentation-fastapi==0.51b0
    - opentelemetry-proto==1.15.0
    - opentelemetry-sdk==1.30.0
    - opentelemetry-semantic-conventions==0.51b0
    - opentelemetry-util-http==0.51b0
    - orjson==3.10.14
    - overrides==7.7.0
    - packaging==24.2
    - pillow==8.3.2
    - pkgutil-resolve-name==1.3.10
    - posthog==3.6.5
    - propcache==0.2.1
    - protobuf==4.25.3
    - pulsar-client==3.5.0
    - pyarrow==19.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pycparser==2.22
    - pydantic-core==2.27.1
    - pydantic-settings==2.8.1
    - pydeck==0.9.1
    - pygments==2.19.1
    - pyjwt==2.10.1
    - pyopenssl==25.0.0
    - pypdf==5.3.0
    - pypika==0.48.9
    - pyproject-hooks==1.2.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyu2f==0.1.5
    - pyyaml==6.0
    - referencing==0.36.2
    - regex==2024.11.6
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - rich==13.9.4
    - rich-toolkit==0.11.3
    - rpds-py==0.22.3
    - rsa==4.9
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.11.4
    - shellingham==1.5.4
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - sqlalchemy==2.0.37
    - starlette==0.46.0
    - sympy==1.13.3
    - tenacity==9.0.0
    - threadpoolctl==3.6.0
    - tiktoken==0.9.0
    - tokenizers==0.21.0
    - toml==0.10.2
    - tomli==2.2.1
    - torch==2.7.0
    - tornado==6.1
    - transformers==4.51.3
    - typer==0.15.2
    - typer-slim==0.15.2
    - typing-inspect==0.9.0
    - typing-utils==0.1.0
    - tzdata==2025.1
    - tzlocal==4.0.2
    - urllib3==2.3.0
    - uvloop==0.21.0
    - watchdog==2.1.6
    - watchfiles==1.0.4
    - websocket-client==1.8.0
    - websockets==15.0
    - wrapt==1.17.0
    - yarl==1.18.0
    - zipp==3.21.0
    - zstandard==0.23.0